github-repository: simplecloudapp/v3-releases
files:
  - release-file: controller-runtime.jar
    output-file: ../controller/controller-runtime.jar
  - release-file: controller-api.jar
    output-file: ../libs/controller-api.jar
