group-id: app.simplecloud.controller
files:
  - artifact: controller-api
    output-file: ../libs/controller-api.jar
  - artifact: controller-runtime
    output-file: ../controller/controller-runtime.jar